fix(convert): Allow more efficient type conversion in presence of overlapping types.
josdejong/typed-function pull request #144
Opened 2022-04-05 11:29 UTC by gwhitney

This is actually built on top of #143, but takes advantage of the fact that v3 is a breaking change to disallow direct access to typed.types and typed.conversions. This way more efficient data structures can be maintained through a functional interface typed.addTypes(), typed.addConversions(), typed.clear(), typed.clearConversions(), making type lookup and conversion significantly more efficient.  It seems like future improvements to typed-function will need to prevent direct manipulation of the internal data structures of types and conversions, so that they can be kept organized in a useful way, so v3 seems like a good opportunity to make that breaking change.

If this is of interest, another small commit will be needed to update the documentation, but I wanted to get something in for you to review as it's getting late and I know that there's interest in completing v3 and moving on.  I've just had so many times that it's been frustrating that there is direct access to typed.types (in particular, that prevented reorganizing the types as a Map from type name to objects with test functions, etc.) that I wanted to make the case that this was a good point to make that breaking change. If you like that, I can polish this up to be really ready to merge tomorrow. Thanks for considering.

2022-04-05 15:43 UTC, josdejong requested changes
Thanks, this is interesting 😎 . It makes sense to change `types` into a map. It is really smart to attach the conversions to the type itself, I like it!

Feedbacks:

1. When introducing such an internal map, we indeed need to introduce public functions like `addTypes` and `addConversion`, and make the internal map private (Ideally they are not accessible at al I think? Hopefully that doesn't complicate testing).
2. I'm very curious how the performance is doing now. I mean, the idea is to to make `typed-function` more efficient, but is there a measurable performance improvement? Can you try that out with this benchmark in mathjs that we used recently?
3. I see you implemented a Map with the types, and the types are linked to each other via `.prev` and `.next` properties. Such a linked-map is relatively complicated, it's easy to introduce bugs somewhere. I'm not sure if it's worth the complexity. A simpler approach could be to just keep both a map and an array side by side? If you are really convinced it is worth it, then it may be good to see if you can extract the logic in a separate class `LinkedMap` and contain the complexity there. What do you think?

2022-04-05 15:59 UTC, gwhitney commented
If you're OK with waiting for tonight and maybe tomorrow as well, I can definitely work on these aspects and would be glad to.
1. Currently the internal Map is not truly inaccessible, it's just on the `_map` property of typed with the initial `_` to mean "don't mess with this." Making it fully invisible to the outside will require a bit more refactoring but if it seems worth it to you let me know and I will be happy to do that.
2. Will run the benchmarks as soon as I can.
3. The doubly-linked list overlay structure is entirely motivated by the 'before' argument to control where new types go in the hieararchy. Even though it's not much used, it does seem like a worthwhile feature going forward as type hierarchies become more complicated. So there are four ways to go: (a) leave this roughly as-is, perhaps with a bit pulling methods out into separate functions to make the "primary" methods shorter/clearer, (b) make another sourcefile LinkedMap.js with its own unit tests and have typed-function import that and use it, (c) try to do the current method with a plain Map and a companion Array using .splice and friends, but that doesn't seem conceptually less complicated to me than (a) -- you still have to be sure you get all the bookkeeping right and consistent between the Map and the Array (which the existing unit tests imply that I have already successfully done between the Map and the link structure); or (d) drop the 'before' argument altogether and rip out the link stuff and always add types at the end immediately before `any`, and figure out the simplest possible way to iterate over the types in index order for the rare times that's necessary. Probably just loop over the types in the random Map order first, filling in an array using the index values, then iterate over the array. Happy to do any of those, just let me know.

And in any case, documentation updating and some commenting and some more unit tests are needed.

2022-04-05 16:05 UTC, josdejong commented
Yes please take it easy 👍 , there is no time pressure from my side. I only want to prevent `v3` from taking too long and block stuff for "months".

2022-04-05 17:10 UTC, gwhitney commented
Ok my priority order on these three items is that I will do (2) as soon as I can get to it and report back the results here; my impression is that you would really prefer (1) over just the "mnemonic for leave this alone" `_map`, so unless I hear otherwise I will do that next; and for (3) I need further guidance from you as to which of (a)-(d) you'd like me to try next. Thanks!

2022-04-06 15:34 UTC, josdejong commented
To reply on https://github.com/josdejong/typed-function/pull/144#issuecomment-1088925304:

1. If it's a lot extra work or causes troubles then let's not do that, then having it exposed as `_map` is fine. If it's little or no extra work it would be nice to make it really inaccessible from outside.
2. 👍 
3. My goal with raising this point is to come up with code that is as easy to read and maintain as possible. My assumption was indeed that (c) would be less complicated. If that will be not the case then there is no point going that route. It sounds good to me to try (d): see if you can drop the before argument to make things simpler again. Would that make (c) interesting again? If a `LinkedMap` is indeed the best way forward, it would be neat to pull the methods into a separate class. Please keep the class inside the `typed-function.js` file and expose it as `typed.LinkedMap` or something like that for unit testing, there is no setup in place to do bundling and everything yet. Thanks!!

2022-04-08 05:23 UTC, gwhitney commented
OK, I have been working quite a bit on the benchmarking for (2). Unfortunately, it involves getting the v11 branch of mathjs working on top of the v3 branch of typed-function (in order to run the benchmark), and unfortunately as we both noted earlier that is a pretty serious amount of work. I now have all the unit tests passing, but to run the benchmarks, I am supposed to build. And that fails... the first error is:
```
[22:11:25] Webpack errors:
../typed-function/typed-function.js
Module not found: Error: Can't resolve '@babel/runtime/helpers/typeof' in '/home/glen/code/typed-function'
resolve '@babel/runtime/helpers/typeof' in '/home/glen/code/typed-function'
  Parsed request is a module
  using description file: /home/glen/code/typed-function/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/glen/code/node_modules doesn't exist or is not a directory
      /home/glen/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /home/glen/code/typed-function/node_modules
        using description file: /home/glen/code/typed-function/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: /home/glen/code/typed-function/package.json (relative path: ./node_modules/@babel/runtime/helpers/typeof)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/glen/code/typed-function/node_modules/@babel/runtime/helpers/typeof doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              /home/glen/code/typed-function/node_modules/@babel/runtime/helpers/typeof.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/glen/code/typed-function/node_modules/@babel/runtime/helpers/typeof.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/glen/code/typed-function/node_modules/@babel/runtime/helpers/typeof.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /home/glen/code/typed-function/node_modules/@babel/runtime/helpers/typeof.json doesn't exist
            as directory
              /home/glen/code/typed-function/node_modules/@babel/runtime/helpers/typeof doesn't exist
[/home/glen/code/node_modules]
[/home/glen/node_modules]
[/home/node_modules]
[/node_modules]
[/home/glen/code/typed-function/node_modules/@babel/runtime/helpers/typeof]
[/home/glen/code/typed-function/node_modules/@babel/runtime/helpers/typeof.wasm]
[/home/glen/code/typed-function/node_modules/@babel/runtime/helpers/typeof.mjs]
[/home/glen/code/typed-function/node_modules/@babel/runtime/helpers/typeof.js]
[/home/glen/code/typed-function/node_modules/@babel/runtime/helpers/typeof.json]
 @ ../typed-function/typed-function.js 10:0-52 41:61-68 102:13-20 1843:27-34 1854:27-34
```
I have exactly 0 experience with webpack. Can you tell if this is just a result of my having installed typed-function from my working clone (i.e., from a local directory, as opposed to a published version from npm)? Or something more sinister? And if it is a result of installing from a local directory, is there any way to work around this and get the build to work?

2022-04-08 07:29 UTC, josdejong commented
That is good and bad news 😄 . Great that you got everything working.

If I get these kind of vague errors, the first thing I try is `npm install` to update all dependencies. If that doesn't work, delete the `node_modules` folder and run a clean `npm install`. In both `mathjs` and `typed-function` projects. 

Can it be related to your latest version of `typed-function` containing some modern JavaScript features that need transpilation? Since the error is related to `@babel/runtime` which is about providing runtime polyfills for missing JS features. Reading the error, Webpack tries to find `@babel/runtime`  inside the `typed-function` project for some reason.

For time sake, if it's just to run a benchmark, you could manually replace the `typed-function.js` file inside `mathjs/node_modules/typed-function` with the version you want to test, or temporarily paste it inside the mathjs project and replace `import 'typed-function'` with `import 'tmp/my-new-typed-function.js'` just for running the benchmark. Just hack around it 😁

2022-04-08 14:02 UTC, gwhitney commented
Ok I will try the npm install route followed by manually overwriting the typed-finction.js in node-modules/typed-function. Will keep you posted.

2022-04-08 15:53 UTC, gwhitney commented
OK, overwriting typed-function.js in node_modules worked. So the results are in. The two runs b11a and b11b attached are with the current mathjs v11 on top of typed-function v2. The two runs bv3a and bv3b are with mathjs v11 modified to be on top of this branch. My main conclusions: the error bars on the timings are somewhat larger than reported (more variation from one run to another with the same code than expected from the error bars as reported), and loading all takes twice as much time with this branch as opposed to v2.

But what this doesn't do is tease out any difference between this branch and the rest of v3 as it stands. I will go ahead and do those benchmarks next. Then we can figure out how to proceed.

2022-04-08 16:52 UTC, gwhitney commented
OK, I was running the benchmarks on top of "plain" v3 and getting inconsistent results. Then it dawned on me that I was running the benchmarks sitting in different places, and that maybe my laptop was "smart" enough to clock the processor differently depending on whether it was on battery or AC power. So here is a full set of benchmarks of all three options, run in close succession in the same physical circumstances:

Typed Function V2, mathjs v11 as it stands today:
[b11c.txt](https://github.com/josdejong/typed-function/files/8453900/b11c.txt)
[b11d.txt](https://github.com/josdejong/typed-function/files/8453901/b11d.txt)

Typed Function V3 as it stands today, mathjs v11 adjusted to have no typed this:
[bv3plain_a.txt](https://github.com/josdejong/typed-function/files/8453905/bv3plain_a.txt)
[bv3plain_b.txt](https://github.com/josdejong/typed-function/files/8453906/bv3plain_b.txt)

Typed Function V3 with this branch, mathjs v11 adjusted to have no typed this:
[bv3c.txt](https://github.com/josdejong/typed-function/files/8453921/bv3c.txt)
[bv3d.txt](https://github.com/josdejong/typed-function/files/8453922/bv3d.txt)

Conclusions this time: timing accuracy not high enough to observe any performance improvement in executing typed functions in typed-function v3 (if there is any); loading is _much_ slower with v3, although apparently consistently somewhat better with this branch. At a rough estimate, the loading slowdown is 2.2x the time in v3 as it stands (as compared to v2), 2x the time in this branch.

The results are not implausible: checking for references and resolving them takes time.

So let me know how you'd like to proceed in light of this data. If you want to pursue v3 along the current lines, then I would say this branch is definitely a go; but let me know if the roughly doubled load times induces you to want to rethink the planned changes for v3 altogether. I will sit tight in terms of further effort on v3 until I hear your thoughts.

2022-04-09 16:14 UTC, gwhitney commented
One more comment: I didn't realize until just now that node has a built in profiler. So if you like the way v3 is shaping up overall but the 2x slowdown is feeling like a deal breaker, let me know and I will try the profiler on the load all task and see if we can see where the time is going and if it could be sped up more. (If you're OK with v3 as is, I am also happy not to bother with profiling. ;-)

2022-04-12 12:45 UTC, josdejong commented
Ai, that is bad news! Having mathjs loading more than 2 times as slow is serious :(.

So if I may summarize, the main changes in v3:
- The refactor in `compareSignatures` and `compareParams` worsens the performance ([#134](https://github.com/josdejong/typed-function/pull/134))
- The refactor of `this` to `typed.referTo` and `typed.referToThis` worsens the performance ([#137](https://github.com/josdejong/typed-function/pull/137))
- The refactor in this PR ([#144](https://github.com/josdejong/typed-function/pull/144)) only improves performance a tiny bit.

Our expectation/hope with these PR's was a better execution time performance and a better API. I do like the API improvements in v3, though it is a bummer that there isn't really any improved execution time. It may be that the simple "(mathjs) evaluate" benchmark isn't extensive enough to cover these improvements well: it probably doesn't trigger any re-dispatch case.

Before drawing any conclusions on how to proceed with v3 (ie. is it worth it), I would love to do a bit of profiling to see whether the v3 approach as a specific new bottleneck that we can (hopefully) tackle. Is it possible to push your mathjs branch with the updated self references so I can do a bit of profiling too on this PR (#144)?

The benchmarking in mathjs is good, as in, it is a real-world test. But it is relatively hard to execute a benchmark when trying to tweak `typed-function`. It would be helpful to have a set of benchmarks in `typed-function` itself too. Shall we add some benchmarks to `typed-function`?

2022-04-12 15:06 UTC, gwhitney commented
> Ai, that is bad news! Having mathjs loading more than 2 times as slow is serious :(.

Well, load.lazy is not measurably slowed down, and that's what we actually do. But yes, load.all is roughly doubled in time. With all of the changes, I wouldn't say "more than" twice as slow.

> So if I may summarize, the main changes in v3:
> 
>     * The refactor in `compareSignatures` and `compareParams` worsens the performance ([#134](https://github.com/josdejong/typed-function/pull/134))
> 
>     * The refactor of `this` to `typed.referTo` and `typed.referToThis` worsens the performance ([#137](https://github.com/josdejong/typed-function/pull/137))
> 
>     * The refactor in this PR ([#144](https://github.com/josdejong/typed-function/pull/144)) only improves performance a tiny bit.

Well, let's be clear: I only targeted three snapshots in my profiling: (A) v2.1.0, (B) the current v3 candidate, and (C) v3+this PR. There are _many_ changes between (A) and (B) (some of them already in develop, such as preferring conversion to 'any', and `typed` not itself being a typed-function), and so I have no attribution as to which of those changes contributes how much to the slowdown. For example, one contributor could be copying the signatures object as opposed to modifying it in place. I could try a bisection to localize where the performance degraded, but the difficulty is that likely portions of mathjs need to be rewritten for each different bisection point, as the api was rather in flux here. But let me know if you think bisection would be helpful, and I will try to embark on it.

(And just in defense of this PR, it seems to improve performance by 10%, which seems more than "a tiny bit" to me...)

> 
> Our expectation/hope with these PR's was a better execution time performance and a better API. I do like the API improvements in v3, though it is a bummer that there isn't really any improved execution time. It may be that the simple "(mathjs) evaluate" benchmark isn't extensive enough to cover these improvements well: it probably doesn't trigger any re-dispatch case.

Well the place I was hoping to see improved execution time was the parse or parse-and-compile tests, since I was thinking those operations do a fair amount of re-dispatch. But the fact is, most of the redispatch is in array operations, and there you already have the various algorithmXX functions picking the proper implementation out of a typed function before executing it repeatedly, so it seems that in practice there is not currently a _lot_ of time wasted in redispatch. And there are a lot of redispatch cases that couldn't really be removed (just the syntax changed, I think for the better), e.g. all of the Unit operations that have to redispatch on the values of the unit objects, since those values can (rightly) be any of the numeric types. And even if we separated those functions into e.g. unaryMinus and unaryMinusNumeric (I say numeric rather than scalar here because units are considered scalars), after the unaryMinus dispatch to the Unit case you would still be doing a unaryMinusNumeric dispatch, which has only a couple fewer cases... The only way to help that would be to have template types in typed-function, so that you could have Unit<number>, Unit<Fraction>, etc, so that no redispatch on the innards would be necessary, you would know what type it was. But even though it would also be nice to have e.g. template Complex<number>, Complex<BigNumber>, etc., that's beyond the scope of this effort. The point is, only a certain chunk, perhaps not even the majority, of redispatches in mathjs became direct calls to another implementation, and the biggest opportunities for this were already handled in the guts of the matrix algorithms. So that's I think why we are not seeing appreciable execution-time improvement, even though I will say that it feels much "cleaner" not to always blindly redispatch to the entire collection of implementations.

> Before drawing any conclusions on how to proceed with v3 (ie. is it worth it), I would love to do a bit of profiling to see whether the v3 approach as a specific new bottleneck that we can (hopefully) tackle. Is it possible to push your mathjs branch with the updated self references so I can do a bit of profiling too on this PR (#144)?

Sure, I will try to bottle it up just a bit and push it. Be prepared, it's a bit of a mess at the moment, I was really just trying to get everything running. When there is something there I will post a bit of a guide here.

> 
> The benchmarking in mathjs is good, as in, it is a real-world test. But it is relatively hard to execute a benchmark when trying to tweak `typed-function`. It would be helpful to have a set of benchmarks in `typed-function` itself too. Shall we add some benchmarks to `typed-function`?

I mean sure, that would be nice, but I don't really have a clue where to start for something that has the richness of mathjs, and in the end, it's performance there we really care about. If you have ideas for internal benchmarks in typed-function, though, by all means add them -- anything would be useful.

2022-04-12 17:50 UTC, gwhitney commented
OK, I have pushed to this (typed-function) repo the latest version of the branch for this PR; that's the version with which I got everything working with mathjs. On the mathjs end, I pushed branch `no_typed_this` -- that will work and pass all tests using the typed function from this branch `fix/convert_maximal`.  And I also pushed branch `no_typed_this_plain_v3` that will work and pass all tests using the typed function as currently in the typed-function branch `v3`. Note that both flavors of "no typed this" in mathjs are on top of v11.

So to sum up, the following combos work and were benchmarked above:

typed-function: v2.1.0  mathjs: develop
typed-function: v3      mathjs: no_typed_this_plain_v3
typed-function: fix/convert_maximal     mathjs: no_typed_this.

Possibly other tweaks will be needed on the mathjs end in the case of a bisection study on the performance of typed-function between v2.1.0 and v3.

My plan is to first run the node profiler on the load all task before launching into such a bisection study. If there's any simple way to just re-boost the performance I'd rather do that and move on.

2022-04-12 18:20 UTC, gwhitney commented
Well, that was a bit of a bust; here's the node profile summary of load all:
```
 [Summary]:
   ticks  total  nonlib   name
     73    7.4%    7.4%  JavaScript
    455   46.2%   46.3%  C++
     45    4.6%    4.6%  GC
      3    0.3%          Shared libraries
    454   46.1%          Unaccounted
```
Hard to optimize anything when half your time is unaccounted for. I guess as soon as I have time -- not today -- I will start the bisection study. (But if you have other suggestions for profiling, let me know.)

2022-04-12 18:27 UTC, gwhitney commented
> Well, that was a bit of a bust; here's the node profile summary of load all (for the fix/convert-maximal -- no_typed_this combo):
> 
> ```
>  [Summary]:
>    ticks  total  nonlib   name
>      73    7.4%    7.4%  JavaScript
>     455   46.2%   46.3%  C++
>      45    4.6%    4.6%  GC
>       3    0.3%          Shared libraries
>     454   46.1%          Unaccounted
> ```
> 
> Hard to optimize anything when half your time is unaccounted for. I guess as soon as I have time -- not today -- I will start the bisection study. (But if you have other suggestions for profiling, let me know.)

2022-04-14 03:58 UTC, gwhitney commented
OK, some news on the benchmarking front. Rather than launch into the bisection approach (which seemed a bit tedious), I decided to first eliminate typed.referTo and typed.referToThis altogether, and make a version of mathjs that doesn't need them at all (but passes _all_ of the existing texts). That also remains slower than develop with typed 2.1.0. Also, to make the comparison clearer, I added a count of how many typed functions are created to the output of the load benchmark. So here are the results:
```
# develop -- typed 2.1.0
mathjs> node test/benchmark/load.js
import, parse, and load time: 347.282ms
load lazy  x 1,402 ops/sec ±1.15% (88 runs sampled)
load all   x 28.95 ops/sec ±5.17% (54 runs sampled)
Load all created 226 typed functions.

# v11 with no refer -- typed v3 with Map and no refer
mathjs> node test/benchmark/load.js
import, parse, and load time: 416.227ms
load lazy  x 1,346 ops/sec ±1.25% (90 runs sampled)
load all   x 13.74 ops/sec ±3.24% (39 runs sampled)
Load all created 283 typed functions.
```

So one piece of "good" news is that refer and referTo are not "big culprits"; things are still much slower without them. So there's something else we did that has slowed load all down a lot. (So that makes doing the bisection seem more promising.)

The other main piece of news is that one of things that has slowed "load al"l down is that without `this`, mathjs creates a lot more typed functions. That's because in a lot of cases in the code, I first create a typed function that has all of the signatures that some former `this` needed to refer to, and then I create the final typed function by merging the first one with the additional signature(s) that had `this`, using explicit calls to the first typed function in place of `this`. Some specific functions even end up getting split into three "layers" this way (typically a numeric layer, a scalar layer in which the Unit signature refers to the numeric, and then a Matrix layer that refers to the scalar layer). I could just use typed.referToSelf exclusively and that should keep the number of typed function creations down, presumably speeding up the "load all." (But that doesn't _mean_ that's what we ultimately want to do). But short of that, I think that it's not fair to say that the new typed-function code is 2x as slow, it's more like (28.95/13.74)*(226/283) = 1.68 times as slow, which is not _quite_ as bad.

So at this point I think I still need to bite the bullet and do the bisection study to see where the big (~68%) increase in load all occurred. I will start that as soon as I can. It may take a few days because I probably need a custom version of mathjs for each point in the bisection.

Finally, I just want to say that because there's already lazy loading, which is barely slowed down, it's not clear to me that we need to get "load all" down to just as fast as typed v2.1 -- the lazy loading means that any individual use of mathjs is only going to pay a fraction of that total slowdown of load all, for whatever functions are actually used. In other words, for functionality that really is helpful, I think there should be some willingness to take advantage of the lazy loading to mean that it's OK for "load all" to slow down somewhat. But I agree that a factor of something like 1.68 to 2 (however you want to score it) in load all is worth investigation; if we figure out that slowdown is inevitable, then you can decide whether it's worth it or what pieces of it are worth it. Hopefully, though, in the end we'll find a way to get most or all of the new functionality without nearly so much slowdown in load all.

2022-04-14 18:07 UTC, josdejong commented
Thanks for all the updates. I'll read up on it asap and also do some profiling, but I'm not sure I'll be able to work on it this (long) Easter weekend.

2022-04-16 00:13 UTC, gwhitney commented
OK, significant news in benchmarking: the primary culprit appears to be the reorganization of the compareParams/compareSignatures code I did for making conversions be preferred to 'any'. My guess is that JavaScript can't optimize iterating through an array of functions calling each one in turn nearly as well as it can optimize one big function with a series of hard-coded checks and short-circuit returns the first time one of the checks reveals a difference between the two params or signatures. So even though having the separate array of "metrics" for each compare function is easy on the eyes to see what's going on, it's definitely not worth the cost. Here are the results, run one right after the other in the same physical setting so they are definitely comparable:

```
# develop:
mathjs> node test/benchmark/load.js
import, parse, and load time: 350.767ms
load lazy  x 1,378 ops/sec ±1.22% (89 runs sampled)
load all   x 28.51 ops/sec ±4.90% (53 runs sampled)

typed-function> git checkout 87fa9ef  # Like develop with just the "prefer conversions to any" change 
mathjs> node test/benchmark/load.js
import, parse, and load time: 375.351ms
load lazy  x 1,385 ops/sec ±1.19% (88 runs sampled)
load all   x 20.82 ops/sec ±4.38% (40 runs sampled)
 ```
Note that is a very big slowdown, but it's not the _full_ factor of two -- but remember that this also uses the identical (develop) mathjs code, so it hasn't had the number of typed-functions created increase significantly because of the "layering" effect from avoiding self-references. So I believe this is the vast majority of the slowdown in typed-function, and I believe that we will be able to fix it.

Once you are looking at this again from your holiday weekend (happy holidays, by the way), let me know how you would like me to proceed in rectifying this situation. The two options I can think of are:

(a) Add additional commit(s) on top of this one returning the implementation style of compareParam/compareSignature to the "one big function with short-circuit returns when it finds a differentiating property" (but with the current _logic_ of these functions) and hope that change returns the benchmarks to acceptable levels, or

(b) Rebuild a new branch "v3prime" to the feature level up to and including this PR starting from current develop, merging the feature branches one at a time but substituting a re-implementation of the "prefer conversion to any" feature with an _implementation_ similar to the develop branch but the _logic_ of the new feature branch. In this approach, I would do a careful benchmark after each feature addition to track and make sure that none of them introduce performance degradation in typed-function (as measured by the _average_ time to load a typed function in "load all," rather than the total time for "load all", since we know the latter will increase at the point that the mathjs code changes to avoid "this" and as a result creates more typed functions.)

Of course, there may be alternate approaches besides either of these and I am open to whatever you would like, just let me know.

   Looking good and looking forward to getting this resolved and v3 released :)

2022-04-19 15:27 UTC, josdejong commented
> happy holidays, by the way

Thanks, was a great, relaxing, sunny weekend 😎 

> OK, significant news in benchmarking: the primary culprit appears to be the reorganization of the compareParams/compareSignatures code I did for making conversions be preferred to 'any'.

The benchmark numbers you post now (https://github.com/josdejong/typed-function/pull/144#issuecomment-1100479112) correspond correspond with those you posted in https://github.com/josdejong/typed-function/pull/134#issuecomment-1074208237, so that makes sense that this is the impact of `compareParams/compareSignatures`. That indeed looks like the biggest culprit.

I ran the `math/no_typed_this_plain_v3` branch with the `typed-function/v3`  branch, and compared that against `mathjs/develop`. I get these kind of numbers: 

```
# mathjs/develop, typed-function/v2.1.0
PS C:\Users\wjosd\projects\mathjs> node .\test\benchmark\load.js
import, parse, and load time: 546.565ms
load lazy  x 1,275 ops/sec ±4.45% (82 runs sampled)
load all   x 28.21 ops/sec ±6.23% (50 runs sampled)

# mathjs/no_typed_this_plain_v3, typed-function/v3
PS C:\Users\wjosd\projects\mathjs> node .\test\benchmark\load.js
import, parse, and load time: 594.326ms
load lazy  x 1,257 ops/sec ±4.68% (82 runs sampled)
load all   x 12.65 ops/sec ±5.93% (36 runs sampled)
```

I have to say I find it hard to draw conclusions since there are so many moving parts right now.

So, how to proceed? Both your approaches (a) and (b) are fine with me. I would love to pick the one that costs the least amount of time and results in an "acceptable" performance. I guess the easiest will be to tackle all of it in this #144. It can be more tricky though since #144 also introduces more new concepts, making it harder to identify and compare performance bottlenecks.

I think for quicker iterations on the benchmarking it may help to create a small benchmark suite in `typed-function` itself, isolated from mathjs (that will also give less moving parts to worry about).

2022-04-19 20:40 UTC, gwhitney commented
Aha, it is consistent with those earlier measures, and I hadn't realized at that time how significant the slowdown it actually showed actually was.

Given your unease/concerns expressed in your last comment, I will rebuild v3 stepwise and document benchmarks with each commit, starting with a faster (if more verbose) implementation of "prefer type conversions to `any`". My goal will be for the cumulative impact of the changes on "load all" time to be less than 10% _per typed function created_ -- hopefully no noticeable slowdown at all in the end, but we will see. I will do as many of the changes that are consistent with mathjs 'develop' branch first, so those timings will be as comparable as possible, and put the referTo stuff last, since that then needs some branch of mathjs to run with, making the timing a little less apples-to-apples.

And yes, it would be great to have internal benchmarks here in typed function but I haven't really a clue about how to create benchmarks that test things nearly as well/significantly as mathjs "load all". So for me the path of least resistance is to just go ahead and benchmark with mathjs. But if you happen to have the time, motivation, and an idea for typed-function benchmarks, I of course will run them as well in my tests.

To facilitate this, I will create a branch `v3a` to be the "alternate v3" and try to document really well and clearly exactly what I merge into it, keeping a running record of benchmarks. Is there any particular place on github that it makes sense to you to keep that info? Create an "issue" to track the progress of `v3a` and just post comments to that as I go?

2022-04-20 06:21 UTC, josdejong commented
Thanks, that sounds like a good plan, thanks a lot 👍

Yes I'll have a look into adding some benchmarks to `typed-function`, I think I can do that tomorrow. It will indeed not give an "absolute" real-world benchmark like the mathjs one, but I think it can be helpful for "relative" benchmarks: change a thing in the code, run the benchmark again to see if things improve or worsen, repeat.

> To facilitate this, I will create a branch v3a to be the "alternate v3" and try to document really well and clearly exactly what I merge into it, keeping a running record of benchmarks. Is there any particular place on github that it makes sense to you to keep that info? Create an "issue" to track the progress of v3a and just post comments to that as I go?

Whatever works handiest :), maybe a GDrive Sheet is handy for that. Or create ths `v3a` branch, and directly create a PR out of it, and document everything in the PR so you see the benchmark results and commits in one place.

2022-04-21 11:44 UTC, josdejong commented
@gwhitney I've created some benchmarks (I noticed that there where already _some_ benchmarks in place), see #146

2022-05-12 09:00 UTC, josdejong commented
@gwhitney we can close this PR and remove the branch, right? It's implemented in #147 and merged now. 

Looking at the [branches page](https://github.com/josdejong/typed-function/branches/all) I think we can cleanup the following branches now:  `fix/convert_maximal`, `fix/convert_minimal`, `feat/no_binding_self_refactor`. Agree?

2022-05-12 14:23 UTC, gwhitney commented
Agree on all counts.

2022-05-12 15:24 UTC, josdejong commented
Ok I'll close this PR and delete the feature branch (and the other two)

2022-05-12 15:24 UTC, closed without merging

2022-05-12 15:25 UTC, josdejong commented
Also deleted the old `v3` branch